app/login/models.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from app.db import db
from app.main.models import PasswordStorage


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    password_storage = db.relationship('PasswordStorage', backref='user', lazy=True)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

app/login/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

app/login/__init__.py
from flask import Blueprint

login_bp = Blueprint('login', __name__, template_folder='templates')

from . import routes

app/login/routes.py
from flask import current_app, flash, redirect, render_template, request, url_for, session
from flask_login import current_user, login_required, login_user, logout_user

from app.db import db
from app.login import login_bp
from app.login.forms import LoginForm, RegistrationForm
from app.login.models import User


@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    if form.validate_on_submit():
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user)
            flash('Login successful', 'success')
            return redirect(url_for('main.index'))
        else:
            flash('Login failed', 'danger')
    return render_template('login/login.html', form=form)


@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out', 'success')
    return redirect(url_for('main.index'))


@login_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        current_app.logger.info(f'Set password for {form.username.data}')

        db.session.add(user)
        db.session.commit()

        flash('Your account has been created!', 'success')
        return redirect(url_for('login.login'))
    return render_template('login/register.html', title='Register', form=form)

app/login/templates/login/login.html
{% extends "base.html" %}

{% block content %}
  <h2>Login</h2>
  <form method="post" action="{{ url_for('login.login') }}">
    {{ form.hidden_tag() }}
    {{ form.csrf_token }}
    <label for="username">Username:</label>
    {{ form.username(size=20) }}
    <br>
    <label for="password">Password:</label>
    {{ form.password(size=20) }}
    <br>
    {{ form.submit() }}
  </form>
{% endblock %}

app/login/templates/login/register.html
{% extends "base.html" %}

{% block content %}
  <h2>Register</h2>
  <form method="post" action="{{ url_for('login.register') }}">
    {{ form.hidden_tag() }}
    {{ form.csrf_token }}
    <div>
      <label for="username">Username:</label>
      {{ form.username(size=20) }}
    </div>
    <div>
      <label for="email">Email:</label>
      {{ form.email(size=20) }}
    </div>
    <div>
      <label for="password">Password:</label>
      {{ form.password(size=20) }}
    </div>
    <div>
      <label for="confirm_password">Confirm Password:</label>
      {{ form.confirm_password(size=20) }}
    </div>
    <div>
      {{ form.submit() }}
    </div>
  </form>
{% endblock %}